### ISSUE TITLE
inputstream adaptive missing on N shield running 18.2 kodi after installing a build.

### ISSUE THREAD

**Issue by TheGridRepo** [xbmc/inputstream.adaptive#258]

**Comment by TheGridRepo** [comment]
rtmp listed in kodi repo but not inputstream adaptive for android

**Comment by peak3d** [comment]
inputstream.adaptive is in general bundled with kodi because of the decrypter shared library files which are not supported by kodi installer / updater on android devices (shared libs must be moved to a special folder). If you build kodi for Android by your self, you'll have to build inputstream.adaptive, too
